name: drift_stream_timer_issue
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.19.2
  drift_flutter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.19.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
